name: Validate Main

on:
  push:
    branches: [main]
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Sleep for 5s
        run: sleep 5
      - name: Check PR branch
        run: |
          BRANCH_NAME="${{ github.ref_name }}"

          if [[ $BRANCH_NAME == *"pr-10"* ]]; then
              exit 1
          fi
      - name: Sleep for 30 seconds
        run: sleep 30
