name: Sleep for 5 minutes

on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display info
        run: |
          pwd
          tree -a -I '.git'
          git status
      - name: Sleep for 5 minutes
        run: sleep 300
