name: Validate PR

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"

          if [[ $PR_TITLE == *"fail"* ]]; then
            exit 1
          fi
